spring:
  application:
    name: balancebite
  config:
    import: optional:classpath:.env

  datasource:
    url: jdbc:postgresql://localhost:5432/balancebite
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: always
      platform: postgres

  jpa:
    database: postgresql
    show-sql: true
    generate-ddl: true
    hibernate:
      # IMPORTANT: The 'ddl-auto' setting determines how Hibernate handles the database schema on startup.
      # Options:
      # - create: Drops and recreates the database schema each time the application starts.
      #           WARNING: This will delete all existing data on every restart.
      #           Use this only for testing or development where data persistence is not required.
      # - update: Updates the existing schema without dropping tables, preserving data between restarts.
      #           Recommended for development if you need to keep existing data.
      # - none: Disables schema management, retaining all data and schema as is.
      # - create-drop: Creates schema at startup but drops it when the application stops.
      ddl-auto: update
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Email configuration for sending notifications
#mail:
#  host: smtp.gmail.com
#  port: 587
#  username: restaurant.bestellingen.app@gmail.com
#  password: your_generated_app_password
#  properties:
#    mail:
#      smtp:
#        auth: true
#        starttls:
#          enable: true

  usda:
    api:
      key: ${USDA_API_KEY}

      file:
        # Directory where uploaded files will be stored.
        # IMPORTANT: Change this path to a suitable directory when deploying to a live server.
        # Example for production: /var/www/uploads/
        upload-dir: uploads/


food:
  fdcIds:
    - "170513"
    - "169287"
    - "169999"
    - "173944"
    - "323505"
    - "169910"
    - "2346409"
    - "2685573"
    - "1999634"
    - "747447"
    - "171705"
    - "169124"
    - "2344766"
    - "173424"
    - "172688"
    - "171409"
    - "171269"
    - "174276"
