spring:
  application:
    name: balancebite
  config:
    import: optional:classpath:.env

  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/balancebite
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: always

# Email configuration for sending notifications
#mail:
#  host: smtp.gmail.com
#  port: 587
#  username: restaurant.bestellingen.app@gmail.com
#  password: your_generated_app_password
#  properties:
#    mail:
#      smtp:
#        auth: true
#        starttls:
#          enable: true

  usda:
    api:
      key: ${USDA_API_KEY}

food:
  fdcIds:
    - "170513"
    - "169287"
    - "169999"
    - "173944"
    - "323505"
    - "169910"
    - "2346409"
    - "2685573"
    - "1999634"
    - "747447"
    - "171705"
    - "169124"
    - "2344766"
    - "173424"
    - "172688"
    - "171409"
    - "171269"
    - "174276"
